---
# Playbook for Tyk API Gateway

- hosts: tyk-local
  remote_user: root
  become: yes
  roles:
    - tyk
  environment:
    http_proxy: http://<user>:<pass>@proxy.example.com:8080
    https_proxy: http://<user>:<pass>@proxy.example.com:8080